NeymarBot:
  Type: "AWS::Lex::Bot"
  Properties:
    Name: "Neymar"
    Description: "Bot para PoC do Amazon Lex"
    IdleSessionTTLInSeconds: 300
    DataPrivacy:
      ChildDirected: false
    BotLocales:
      - LocaleId: pt_BR
        NluConfidenceThreshold: 0.40
        SlotTypes:
          - Name: "ProblemCatalog"
            Description: "Catálogo de problemas"
            SlotTypeValues:
              - SampleValue:
                  Value: "Ações"
              - SampleValue:
                  Value: "Visualizar recursos"
            ValueSelectionSetting:
              ResolutionStrategy: TOP_RESOLUTION
          - Name: "DoubtCatalog" 
            Description: "Catálogo de dúvidas"
            SlotTypeValues:
              - SampleValue:
                  Value: "Como utilizar um recurso"
            ValueSelectionSetting:
              ResolutionStrategy: TOP_RESOLUTION
        Intents:
          - Name: "Greeting"
            Description: "Saudação inicial ao bot"
            SampleUtterances:
              - Utterance: "Olá"
              - Utterance: "Oi"
              - Utterance: "Ola Neymar"
            IntentClosingSetting:
              ClosingResponse:
                MessageGroupsList:
                  - Message:
                      PlainTextMessage:
                        Value: "Oi eu sou o Neymar! Como posso ajudar você hoje?\nVamos falar sobre um dúvida ou problema?"
                    Variations:
                      - PlainTextMessage:
                          Value: "Olá eu sou o Neymar! O que eu posso fazer por você hoje?\nVamos falar sobre um dúvida ou problema?"
          - Name: "Problem"
            Description: "Definir o tipo de problema"
            # DialogCodeHook:
            #   Enabled: true
            FulfillmentCodeHook:
              Enabled: true
            SampleUtterances:
              - Utterance: "problema"
            InitialResponseSetting:
              InitialResponse:
                MessageGroupsList:
                  - Message:
                      PlainTextMessage:
                        Value: "Sinto muito que você esteja passando por um problema!"
            SlotPriorities:
              - Priority: 1
                SlotName: "ProblemCatalog"
            Slots:
              - Name: "ProblemCatalog"
                SlotTypeName: "ProblemCatalog"
                ValueElicitationSetting:
                  SlotConstraint: "Required"
                  PromptSpecification:
                    MessageGroupsList:
                      - Message:
                          PlainTextMessage:
                            Value: "Onde você está enfrentando o problema?\n- Ações\n- Visualizar recursos"
                    MaxRetries: 3
          - Name: "Doubt"
            Description: "Definir o tipo de dúvida"
            # DialogCodeHook:
            #   Enabled: true
            FulfillmentCodeHook:
              Enabled: true
            SampleUtterances:
              - Utterance: "dúvida"
            SlotPriorities:
              - Priority: 1
                SlotName: "DoubtCatalog"
            Slots:
              - Name: "DoubtCatalog"
                SlotTypeName: "DoubtCatalog"
                ValueElicitationSetting:
                  SlotConstraint: "Required"
                  PromptSpecification:
                    MessageGroupsList:
                      - Message:
                          PlainTextMessage:
                            Value: "Sobre o quê é a sua dúvida?\n- Como utilizar um recurso"
                    MaxRetries: 3
          - Name: "FallbackIntent"
            Description: "Default intent when no other intent matches"
            ParentIntentSignature: "AMAZON.FallbackIntent"
    RoleArn:
      Fn::GetAtt: [NeymarBotRole, Arn]
